### ISSUE TITLE
How can i use an animation with JS?

### ISSUE THREAD

**Issue by kei0719** [akveo/eva-icons#15]
Hello. first of all, it's good library the evaicons.

I have one question, how can i use an animation ( available 4 types ) with JS?

**Comment by denStrigo** [comment]
Hi @kei0719 thank you for your feedback.

In order to apply the animation to an icon, you can add `data-eva-animation` attribute and pass animation type `zoom | pulse | shake | flip`, animation will be work by hover.
e.g. `<i data-eva="github" data-eva-animation="zoom"></i>`

Also you can add animation as property in replace method `eva.replace({ animation: { type: 'zoom | pulse | shake | flip'})`, animation should apply for all icons on a page.

Animation and other available property will be added to the documentation soon.

**Comment by kei0719** [comment]
Excellent! Thank you.
