### ISSUE TITLE
Where's the CSS file if I want to use Icon Font

### ISSUE THREAD

**Issue by jiyinyiyong** [akveo/eva-icons#22]
I'm not using React or Webpack, sadly, I want to use SVG but turned out icon font would be better option. Browsed the folders, I got the question.

Lovely icons BTW.

**Comment by denStrigo** [comment]
HI @jiyinyiyong thank you for your feedback.

Eva Icons fonts are parts of the [eva-icins](https://www.npmjs.com/package/eva-icons) npm package. In order to use fonts you should install npm package and depend on your build tools, include fonts in your project, path to fonts `node_modules/eva-icons/style/eva-icons.css` or if you use scss `node_modules/eva-icons/style/scss/eva-icons.scss`. Also you can link fonts directly in you html file `<link rel="stylesheet" href="/node_modules/eva-icons/style/eva-icons.css">`
But if you don't use any build tools you can download the latest compressed package file by the link https://registry.npmjs.org/eva-icons/-/eva-icons-1.0.2.tgz all font in the folder `style`

**Comment by chenyong** [comment]
Thanks. Now I find the CSS files.

**Comment by denStrigo** [comment]
You are welcome.

**Comment by jiyinyiyong** [comment]
It appears to me the icons do not looks like what I expected:

![image](https://user-images.githubusercontent.com/449224/48301986-3e871b00-e531-11e8-9a13-2e5b8f336ceb.png)
![image](https://user-images.githubusercontent.com/449224/48301990-49da4680-e531-11e8-876d-ff0af814d540.png)

It looks like this in the home page:

![image](https://user-images.githubusercontent.com/449224/48302001-6d9d8c80-e531-11e8-8a4e-96937cb2f68e.png)
